general_model = 'general-v1.3'
ingredients_model = 'food-items-v1.0'
forbidden = {
    'anchovy': 'ansjovis',
    'aspic': 'aspic',
    'baby back ribs': 'rug ribben',
    'bacon': 'spek',
    'barbecue': 'barbecue',
    'bass': 'bas',
    'beef': 'rundvlees',
    'beef carpaccio': 'carpaccio van runderen',
    'beef steak': 'biefstuk',
    'beef tartare': 'rundvleestartaar',
    'bird': 'vogel',
    'blood sausage': 'bloedworst',
    'bratwurst': 'Bratwurst',
    'bream': 'brasem',
    'brisket': 'borst',
    'broil': 'braden',
    'calamari': 'Calamari',
    'canape': 'Canape',
    'carp': 'karper',
    'carpaccio': 'Carpaccio',
    'casserole': 'braadpan',
    'caviar': 'kaviaar',
    'ceviche': 'Ceviche',
    'chevre': 'Chevre',
    'chicken': 'kip',
    'chicken breast': 'kipfilet',
    'chicken curry': 'kip-curry',
    'chicken leg': 'kippen been',
    'chicken quesadilla': 'chicken quesadilla',
    'chicken wings': 'kippenvleugels',
    'chorizo': 'Chorizo',
    'clam': 'Clam',
    'clam chowder': 'mosselvissoep',
    'cockle': 'Kokkel',
    'cooked meat': 'gekookt vlees',
    'corned beef': 'corned beef',
    'crab': 'krab',
    'crab cakes': 'crab cakes',
    'crayfish': 'rivierkreeft',
    'croquette': 'Kroket',
    'cutlet': 'kotelet',
    'cuttlefish': 'inktvis',
    'deviled eggs': 'deviled eggs',
    'drumstick': 'trommelstok',
    'duck': 'eend',
    'eel': 'paling',
    'escargots': 'Escargots',
    'fat hen': 'dikke kip',
    'filet mignon': 'filet mignon',
    'fillet': 'filet',
    'fillet of sole': 'filet van tong',
    'fish': 'vis',
    'fish and chips': 'Fish and chips',
    'fish fillet': 'visfilet',
    'fish fingers': 'vissticks',
    'flatfish': 'platvis',
    'foie gras': 'Ganzenlever',
    'fondue': 'fondue',
    'fowl': 'kip',
    'frankfurters': 'Worstjes',
    'fried calamari': 'gefrituurde inktvisringen',
    'goose': 'gans',
    'goulash': 'goulash',
    'gravy': 'jus',
    'grilled salmon': 'gegrilde zalm',
    'ground beef': 'gehakt',
    'haddock': 'schelvis',
    'halibut': 'heilbot',
    'ham': 'ham',
    'hamburger': 'Hamburger',
    'herring': 'haring',
    'horse gram': 'paarden gram',
    'hot dog': 'hotdog',
    'kebab': 'kebab',
    'kingfish': 'Kingfish',
    'kipper': 'Kipper',
    'lamb': 'lam',
    'lamb chops': 'lamskoteletjes',
    "lamb's quarters": 'lamskwarten',
    'lard': 'reuzel',
    'linguine': 'Linguine',
    'link sausages': 'link worsten',
    'liver pate': 'leverpastei',
    'lobster': 'kreeft',
    'lobster bisque': 'kreeftenbisque',
    'loin': 'Loin',
    'lox': 'Lox',
    'lunchmeat': 'lunch vlees',
    'mackerel': 'makreel',
    'marinated herring': 'gemarineerde haring',
    'marrow': 'merg',
    'meat': 'vlees',
    'meat pie': 'vleestaart',
    'meat sauce': 'vleessaus',
    'meatball': 'Gehaktbal',
    'meatloaf': 'Gehaktbrood',
    'mince': 'Gehakt',
    'mussel': 'mossel',
    'mutton': 'Schaap',
    'nugget': 'Nugget',
    'octopus': 'Octopus',
    'oyster': 'oester',
    'pancetta': 'Pancetta',
    'papillote': 'Papillote',
    'pate': 'Paté',
    'pepperoni': 'Pepperoni',
    'perch': 'baars',
    'pike': 'snoek',
    'pilchard': 'Pelser',
    'plaice': 'schol',
    'pork': 'varkensvlees',
    'pork chop': 'varkensvlees',
    'pork pie': 'varkensvleespastei',
    'pot roast': 'stoofpot',
    'poutine': 'Poutine',
    'prawn': 'garnaal',
    'prime rib': 'prime rib',
    'prosciutto': 'Prosciutto',
    'rib': 'rib',
    'roast beef': 'rosbief',
    'roe': 'Roe',
    'roulade': 'roulade',
    'salami': 'salami',
    'salmon': 'Zalm',
    'salmon steak': 'Zalm steak',
    'salted fish': 'gezouten vis',
    'sardine': 'sardine',
    'sashimi': 'Sashimi',
    'sausage': 'worst',
    'scallop': 'Coquille',
    'scampi': 'Scampi',
    'sea bass': 'zeebaars',
    'sea perch': 'zeebaars',
    'seafood': 'Seafood',
    'shellfish': 'Schelpdieren',
    'shish kebab': 'shish kebab',
    'shrimp': 'Garnalen',
    'sirloin': 'Ossenhaas',
    'skewer': 'vleespen',
    'smoked fish': 'gerookte vis',
    'smoked salmon': 'gerookte zalm',
    'smoked sausage': 'gerookte worst',
    'snapper': 'Snapper',
    'spare ribs': 'spareribs',
    'squid': 'inktvis',
    'steak': 'biefstuk',
    'stout': 'stout',
    'sturgeon': 'steur',
    'suet': 'niervet',
    'sushi': ' sushi',
    'tartare': 'tartaar',
    'tenderloin': 'rosse buurt',
    'teriyaki': 'teriyaki',
    'tongue': 'tong',
    'trout': 'forel',
    'tuna': 'tonijn',
    'tuna tartare': 'tonijn tartaar',
    'turkey': 'kalkoen',
    'turkey breast': 'kalkoenfilet',
    'veal': 'kalfsvlees',
    'veal cutlet': 'kalfsschnitzel',
    'venison': 'hertevlees'
}
translate_ingredient_dict = {
    'alcohol': 'alcohol',
    'ale': 'ale',
    'alfalfa sprouts': 'alfalfa',
    'almond': 'amandel',
    'angel-hair pasta': 'spaghettislierten',
    'anise': 'anijs',
    'aonori': 'aonori',
    'apple': 'appel',
    'apple sauce': 'appelmoes',
    'apricot pits': 'abrikozenpitten',
    'artichoke': 'artisjok',
    'arugula': 'rucola',
    'asparagus': 'asperge',
    'aubergine': 'aubergine',
    'avocado': 'avocado',
    'azuki bean' : 'bruine bonen',
    'bagel': 'bagel',
    'baguette': 'stokbrood',
    'baked beans': 'witte bonen',
    'baklava': 'baklava',
    'balsamic': 'balsamico',
    'bamboo shoots': 'bamboescheuten',
    'banana': 'banaan',
    'barbecue sauce': 'barbecuesaus',
    'barley': 'gerst',
    'basil': 'basilicum',
    'bay leaf': 'laurierblad',
    'beancurd': 'tofu',
    'beans': 'bonen',
    'beer': 'bier',
    'beet': 'bieten',
    'beet root': 'rode bieten',
    'berry': 'bessen',
    'bilberry': 'blauwe bosbes',
    'biscuits': 'biscuits',
    'bitter gourd': 'bittere pompoen',
    'bitter melon': 'bittere meloen',
    'black beans': 'zwarte bonen',
    'black coffee': 'koffie',
    'black currant': 'zwarte bes',
    'black tea': 'zwarte thee',
    'blackberry': 'bramen',
    'blood orange': 'bloedsinaasappel',
    'blue cheese': 'blauwe kaas',
    'blueberry': 'bosbes',
    'bok choy': 'chinese kool',
    'boysenberry': 'boysenberry',
    'bran': 'zemelen',
    'brandy': 'brandewijn',
    'bread': 'brood',
    'bread rolls': 'broodjes',
    'breadcrumb': 'paneermeel',
    'breadfruit': 'smerig aziatisch fruit',
    'breadstick': 'soepstengels',
    'brie': 'brie',
    'brinjal': 'aubergine',
    'brioche': 'broodje',
    'brittle': 'bros',
    'broad beans': 'tuinbonen',
    'broccoli': 'broccoli',
    'broccolini': 'broccoli',
    'broth': 'bouillon',
    'brown bread': 'bruin brood',
    'brown rice': 'bruine rijst',
    'brownie': 'brownie',
    'brulee': 'brulee',
    'bruschetta': 'bruschetta',
    'brussels sprout': 'spruitjes',
    'buckwheat': 'boekweit',
    'bun': 'broodje',
    'burdock': 'klit',
    'burrito': 'burrito',
    'butter': 'boter',
    'buttercream': 'boter',
    'cabbage': 'kool',
    'cake': 'cake',
    'cake mix': 'cake mix',
    'cake pop': 'cake lolly',
    'camembert': 'camembert',
    'candy': 'snoep',
    'candy apple': 'snoep appel',
    'candy bar': 'snoepreep',
    'cantaloupe': 'meloen',
    'cappuccino': 'cappuccino',
    'caramel': 'karamel',
    'caramel apple': 'karamelappel',
    'caraway': 'karwijzaad',
    'cardamom': 'kardemom',
    'carrot': 'wortel',
    'carrot cake': 'worteltaart',
    'cashew': 'cashewnoten',
    'cassava': 'cassave',
    'cauliflower': 'bloemkool',
    'cayenne': 'cayenne',
    'cayenne pepper': 'Cayenne peper',
    'celeriac': 'knolselderij',
    'celery': 'selderij',
    'celtuce': 'stengelsla',
    'cereal': 'granen',
    'cereal bar': 'mueslireep',
    'champagne': 'champagne',
    'chard': 'snijbiet',
    'chayote': 'avocado',
    'cheddar': 'cheddarkaas',
    'cheese': 'kaas',
    'cherimoya': 'vies fruit',
    'cherry': 'kers',
    'cherry tomato': 'cherrytomaten',
    'chestnut': 'kastanje',
    'chickpeas': 'kikkererwten',
    'chili': 'chili',
    'chili pepper': 'chilipeper',
    'chili powder': 'chilipoeder',
    'chili sauce': 'chilisaus',
    'chinese artichoke': 'artisjok',
    'chips': 'frietjes',
    'chives': 'bieslook',
    'chocolate': 'chocola',
    'chocolate bar': 'chocoladereep',
    'chocolate candy': 'chocolade',
    'chocolate cookie': 'chocoladekoekje',
    'chocolate ice cream': 'chocolade-ijs',
    'chocolate mousse': 'chocolademousse',
    'churros': 'churros',
    'chutney': 'chutney',
    'ciabatta': 'ciabatta',
    'cider': 'cider',
    'cilantro': 'koriander',
    'cinnamon': 'kaneel',
    'cinnamon roll': 'kaneelbroodje',
    'citron': 'citroen',
    'citrus': 'citrus',
    'clementine': 'clementine',
    'cloudberry': 'bergframbozen',
    'cloves': 'kruidnagel',
    'cocktail': 'cocktail',
    'cocoa': 'cacao',
    'coconut': 'kokosnoot',
    'coffee': 'koffie',
    'cognac': 'cognac',
    'coke': 'cola',
    'cole slaw': 'coleslaw',
    'coleslaw': 'coleslaw',
    'collards': 'sla',
    'common bean': 'bonen',
    'common purslane': 'postelein',
    'compote': 'compote',
    'cookie': 'koekje',
    'coriander': 'koriander',
    'corn': 'mais',
    'corn bread': 'maisbrood',
    'corn salad': 'maissalade',
    'cornflakes': 'cornflakes',
    'cottage cheese': 'kwark',
    'coulis': 'coulis',
    'courgette': 'courgette',
    'couscous': 'couscous',
    'cracker': 'cracker',
    'cranberries': 'veenbes',
    'cranberry': 'cranberry',
    'cranberry sauce': 'cranberrysaus',
    'cream': 'room',
    'cream cheese': 'roomkaas',
    'creme brulee': 'creme brulee',
    'crepe': 'crepe',
    'cress': 'tuinkers',
    'crispbread': 'knäckebröd',
    'croissant': 'croissant',
    'croque madame': 'tosti',
    'crouton': 'crouton',
    'crumble': 'crumble',
    'crunch': 'crunch',
    'crust': 'korst',
    'cucumber': 'komkommer',
    'cumin': 'komijn',
    'curd': 'wrongel',
    'currant': 'bes',
    'curry': 'kerrie',
    'custard': 'custard',
    'date': 'dadel',
    'dill': 'dille',
    'dolichos bean': 'dolichos bean',
    'doughnut': 'donut',
    'dragonfruit': 'dragonfruit',
    'dried apricot': 'gedroogde abrikoos',
    'dried fruit': 'gedroogd fruit',
    'durian': 'vies aziatisch fruit',
    'edam cheese': 'Edammer',
    'egg': 'ei',
    'egg white': 'eiwit',
    'egg yolk': 'eigeel',
    'eggplant': 'aubergine',
    'elderberry': 'vlierbes',
    'elephant garlic': 'knoflook',
    'emmental': 'emmentaler',
    'endive': 'andijvie',
    'espresso': 'espresso',
    'falafel': 'falafel',
    'farfalle': 'farfalle',
    'fava beans': 'tuinbonenfeest',
    'fennel': 'venkel',
    'fettuccine': 'fettuccine',
    'fig': 'vijgen',
    'fish steak': 'vlaai',
    'flan': 'flan',
    'flatbread': 'flatbread',
    'flour': 'meel',
    'fluted pumpkin': 'pompoen',
    'focaccia': 'focaccia',
    'french beans': 'bonen',
    'french bread': 'stokbrood',
    'french fries': 'frietjes',
    'french onion soup': 'uiensoep',
    'french toast': 'wentelteefjes',
    'fried egg': 'gefrituurd ei',
    'fried rice': 'rijst',
    'frittata': 'frittatabeignet',
    'fritter': 'beignet',
    'frozen peas': 'erwten',
    'frozen yogurt': 'frozen yogurt',
    'fruit tea': 'thee',
    'fruitcake': 'cake',
    'fudge': 'fudge',
    'fusilli': 'Fusilli',
    'galangal': 'Laos',
    'galette': 'Galette',
    'garam masala': 'garam masala',
    'garbanzo': 'Garbanzo',
    'garlic': 'knoflook',
    'garlic bread': 'knoflookbrood',
    'garlic chives': 'knoflookteentjes',
    'garlic sauce': 'knoflooksaus',
    'gazpacho': 'gazpacho',
    'gelatin': 'gelatine',
    'gherkin': 'augurk',
    'gin': 'gin',
    'ginger': 'gember',
    'ginger ale': 'gemberbier',
    'gingerbread': 'peperkoek',
    'gnocchi': 'gnocchi',
    'goats cheese': 'geitenkaas',
    'goji berry': 'bessen',
    'gooseberry': 'kruisbes',
    'gorgonzola': 'gorgonzola',
    'gouda': 'Gouda',
    'gouda cheese': 'Gouda',
    'gourd': 'kalebas',
    'grain': 'granen',
    'granola': 'muesli',
    'granola bar': 'mueslireep',
    'grape': 'druif',
    'grape jelly': 'druivengelei',
    'grapefruit': 'grapefruit',
    'gravy': 'Griekse salade',
    'green onion': 'groene peper',
    'green pepper': 'tosti',
    'green tea': 'thee',
    'grilled cheese sandwich': 'tosti',
    'grissini': 'soepstengels',
    'groats': 'grutten',
    'grub': 'rooien',
    'guacamole': 'guacamole',
    'guava': 'guava',
    'habanero pepper': 'habanero peper',
    'hamburger bun': 'hamburgerbroodje',
    'hash': 'hash',
    'hay': 'hooi',
    'hazelnut': 'hazelnoot',
    'herb': 'kruid',
    'herbal tea': 'kruidenthee',
    'honey': 'honing',
    'honeydew melon': 'honingmeloen',
    'horse radish': 'mierikswortel',
    'hot chocolate': 'warme chocolademelk',
    'hot dog bun': 'hotdogbroodje',
    'hot pepper': 'hete peper',
    'hot sauce': 'hete saus',
    'huckleberry': 'blauwe bessen',
    'hummus': 'hummus',
    'ice': 'ijs',
    'ice cream': 'ijsje',
    'iceberg lettuce': 'ijsbergsla',
    'iced tea': 'ijsthee',
    'indian pea': 'Indiase erwt',
    'indian tea': 'Indiase thee',
    'italian dressing': 'Italiaanse dressing',
    'ivy gourd': 'klimop kalebas',
    'jackfruit': 'jackfruit',
    'jalapeno': 'jalapeno',
    'jam': 'jam',
    'jelly': 'gelei',
    'jelly beans': 'snoepjes',
    'jerusalem artichoke': 'artisjok',
    'jordan almonds': 'amandelen',
    'juice': 'sap',
    'juniper berry': 'jeneverbesbes',
    'kale': 'boerenkool',
    'ketchup': 'ketchup',
    'kettle corn': 'mais',
    'kidney bean': 'kidneybonen',
    'kiwi fruit': 'kiwi fruit',
    'kohlrabi': 'koolraap',
    'lager': 'pils',
    "lamb's lettuce": 'veldsla',
    'lavender': 'lavendel',
    'leek': 'prei',
    'legume': 'peulvrucht',
    'lemon': 'citroen',
    'lemon peel': 'citroenschil',
    'lemonade': 'limonade',
    'lemongrass': 'citroengras',
    'lentil': 'linze',
    'lettuce': 'sla',
    'licorice': 'drop',
    'lima bean': 'limaboon',
    'lime': 'limoen',
    'liqueur': 'likeur',
    'liquor': 'sterke drank',
    'lollipop': 'lolly',
    'loquat': 'perzik',
    'lotus root': 'lotuswortel',
    'luffa': 'luffa',
    'lychee': 'Lychee',
    'm&m': 'M & M',
    'macadamia nut': 'macadamia noot',
    'macaron': 'macaron',
    'macaroni': 'macaroni',
    'macaroon': 'bitterkoekje',
    'maize': 'mais',
    'malabar spinach': 'spinazie',
    'malt': 'mout',
    'mandarin orange': 'sinaasappel',
    'mango': 'mango',
    'maple syrup': 'ahornsiroop',
    'margarine': 'margarine',
    'marinated cucumber': 'komkommer',
    'marionberry': 'Marionberry',
    'marjoram': 'marjolein',
    'marmalade': 'marmelade',
    'marron': 'Marron',
    'marshmallow': 'marshmallow',
    'martini': 'martini',
    'marzipan': 'marsepein',
    'mashed potatoes': 'aardappelpuree',
    'mayonnaise': 'mayonaise',
    'mead': 'mede',
    'melon': 'meloen',
    'meringue': 'meringue',
    'milk': 'melk',
    'milk chocolate': 'melkchocolade',
    'millet': 'gierst',
    "miner's lettuce": 'mijnsla',
    'mint': 'munt',
    'mozzarella': 'mozzarella',
    'muesli': 'muesli',
    'muesli bar': 'mueslibar',
    'muffin': 'muffin',
    'mulberry': 'moerbei',
    'mung bean': 'bonen',
    'mushroom': 'champignon',
    'mustard': 'mosterd',
    'nachos': "Nacho's",
    'napa cabbage': 'kool',
    'nectar': 'nectar',
    'nectarine': 'nectarine',
    'new zealand spinach': 'spinazie',
    'noodle': 'noodles',
    'nougat': 'noga',
    'nut': 'noot',
    'nutmeg': 'nootmuskaat',
    'oat': 'haver',
    'oatmeal': 'havermout',
    'oatmeal cereal': 'havermoutgraan',
    'oatmeal cookie': 'havermout koekje',
    'oil': 'olie',
    'okra': 'okra',
    'olive': 'olijf',
    'olive oil': 'olijfolie',
    'omelet': 'omelet',
    'omelette': 'omelet',
    'onion': 'ui',
    'onion rings': 'uienringen',
    'orange': 'sinaasappel',
    'orange juice': 'sinaasappelsap',
    'orange squash': 'sinaasappelpompoen',
    'oregano': 'oregano',
    'pak choy': 'pak choy',
    'panna cotta': 'panna cotta',
    'papaya': 'papaja',
    'paprika': 'paprika',
    'parfait': 'Parfait',
    'parmesan': 'parmezaanse kaas',
    'parsley': 'peterselie',
    'parsnip': 'pastinaak',
    'passionfruit': 'passievrucht',
    'pasta': 'pasta',
    'pea': 'erwt',
    'peach': 'perzik',
    'peanut': 'pinda',
    'peanut butter': 'pindakaas',
    'pear': 'pindakaas',
    'pecan': 'pecannoot',
    'penne': 'penne',
    'pepper': 'paprika',
    'peppercorn': 'peperkorrel',
    'peppermint': 'pepermuntbaars',
    'pesto': 'pesto',
    'pickle': 'augurk',
    'pickled cucumber': 'augurk',
    'pigeon pea': 'erwt',
    'pine nut': 'pijnboomnoot',
    'pineapple': 'ananas',
    'pistachio': 'pistache',
    'pita bread': 'pita brood',
    'plain flour': 'meel',
    'plum': 'Pruim',
    'pomegranate': 'granaatappel',
    'pomelo': 'pomelo',
    'popcorn': 'Popcorn',
    'poppy seed roll': 'maanzaadbroodje',
    'popsicle': 'Ijslolly',
    'porridge': 'pap',
    'potato': 'aardappel',
    'potato onion': 'ui',
    'praline': 'praline',
    'pretzel': 'pretzel',
    'prune': 'pruim',
    'prussian asparagus': 'asperges',
    'pudding': 'pudding',
    'pumpkin': 'pompoen',
    'pumpkin seeds': 'pompoenpitten',
    'puree': 'puree',
    'quinoa': 'quinoaradijs',
    'radicchio': 'radijs',
    'radish': 'radijs',
    'raisin': 'rozijn',
    'raisin bread': 'rozijnenbroodramboetan',
    'ramen': 'ramen',
    'raspberry': 'framboos',
    'ravioli': 'ravioli',
    'red cabbage': 'rode kool',
    'red pepper': 'rode peper',
    'red wine': 'rode wijn',
    'redcurrant':  'rode bes',
    'relish': 'relish',
    'rhubarb': 'rabarber',
    'rice': 'rijst',
    'rice flake': 'rijstvlokkenRicotta',
    'ricotta': 'ricotta',
    'risotto': 'risottorijst',
    'romaine': 'sla',
    'roquefort': 'roquefort',
    'rose': 'rozenblaadjes',
    'rosemary': 'rozemarijn',
    'rum': 'rum',
    'runner bean': 'bonen',
    'rutabaga': 'roggebrood',
    'rye': 'koolraap',
    'saffron': 'saffraan',
    'sage': 'salie',
    'sake': 'sake',
    'salad': 'sla',
    'salad dressing': 'dressing',
    'salmonberry': 'besje',
    'salsa': 'salsa',
    'salt': 'zout',
    'samphire': 'zeekraal',
    'sandwich': 'brood',
    'satsuma': 'mandarijn',
    'sauerkraut': 'zuurkool',
    'sausage roll': 'bladerdeeg',
    'scallion': 'bosui',
    'scone': 'scone',
    'scrambled': 'scrambled',
    'sea beet': 'kool',
    'sea grape': 'druif',
    'sea kale': 'kool',
    'sea lettuce': 'sla',
    'seaweed salad': 'zeewier',
    'sesame roll': 'broodje',
    'sauce': 'iets van een sausje',
    'sesame seed': 'sesamzaadjes',
    'shallot': 'sjalot',
    'shandy': 'shandy',
    'sherbet': 'sorbet',
    'skirret': 'Suikerwortel',
    'slaw': 'slaw',
    'sliced loaf': 'boterham',
    'smoothie': 'smoothie',
    'snap pea': 'erwt',
    'snow pea': 'erwt',
    'soda': 'frisdrank',
    'sorbet': 'sorbet',
    'sorrel': 'sla',
    'souffle': 'souffle',
    'sour cabbage': 'zure kool',
    'sour cream': 'zure room',
    'sourdough bread': 'zuurdesembrood',
    'soy': 'zaad',
    'soy sauce': 'sojasaus',
    'spearmint': 'munt',
    'spinach': 'spinazie',
    'split peas': 'spliterwten',
    'sponge cake': 'biscuitgebak',
    'spongecake': 'spongecake',
    'spring onion': 'lente-ui',
    'spring rolls': "loempia's",
    'sprinkles': 'hagelslag',
    'sprouts': 'Spruiten',
    'spuds': 'piepers',
    'squash': 'meloen',
    'squash blossoms': 'pompoenbloesems',
    'star fruit': 'stervrucht',
    'stir-fry': 'roerbak',
    'strawberry': 'aardbei',
    'string bean': 'snijboon',
    'strudel': 'strudel',
    'sultanas': 'rozijnen',
    'summer purslane': 'zomerpostelein',
    'summer squash': 'courgette',
    'sundae': 'Ijscoupe',
    'sunflower': 'zonnebloem',
    'sunflower seeds': 'zonnebloemzaden',
    'swede': 'koolraap',
    'sweet cherry': 'kers',
    'sweet corn': 'mais',
    'sweet pepper': 'paprika',
    'sweet potato': 'zoete aardappel',
    'sweet-and-sour sauce': 'zoetzure saus',
    'swiss chard': 'snijbiet',
    'swiss cheese': 'Zwitserse kaas',
    'syrup': 'siroop',
    'tacos': 'tacos',
    'tagliatelle': 'tagliatelle',
    'tangerine': 'mandarijn',
    'tartlet': 'taartje',
    'tea': 'thee',
    'tempura': 'tempura',
    'tepary bean': 'bonen',
    'tequila': 'tequila',
    'thyme': 'tijm',
    'tigernut': 'tijgernoten',
    'toast': 'geroosterd brood',
    'toffee': 'toffee',
    'tofu': 'tofu',
    'tomato': 'tomaat',
    'tomato sauce': 'tomatensaus',
    'tonic': 'tonic',
    'torte': 'Taart',
    'tortellini': 'tortellini',
    'tortilla chips': 'tortilla chips',
    'tree onion': 'boomui',
    'truffle': 'truffel',
    'tuber': 'knol',
    'turmeric': 'kurkuma',
    'turnip': 'raap',
    'tzatziki': 'tzatziki',
    'ugli fruit': 'lelijk fruit',
    'urad bean': 'bonen',
    'velvet bean': 'fluwelen boon',
    'vermicelli': 'vermicelli',
    'vermouth': 'vermout',
    'vinaigrette': 'Vinaigrette',
    'vinegar': 'azijn',
    'vino': 'wijn',
    'vodka': 'wodka',
    'wafer': 'wafeltje',
    'waffle': 'wafel',
    'walnut': 'okkernoot',
    'wasabi': 'wasabi',
    'water': 'water',
    'water caltrop': 'water caltrop',
    'water chestnut': 'water kastanje',
    'water spinach': 'water spinazie',
    'watercress': 'waterkers',
    'watermelon': 'watermeloen',
    'welsh onion': 'ui',
    'wheat': 'tarwe',
    'wheat bread': 'tarwebrood',
    'wheat flake': 'tarweschilfer',
    'whey': 'wei',
    'whipped cream': 'slagroom',
    'whisky': 'whisky',
    'white sauce': 'witte saus',
    'white wine': 'witte wijn',
    'whoopie pie': 'whoopie taart',
    'whortleberry': 'blauwe bosbes',
    'wiener': 'Wiener',
    'wild leek': 'wilde prei',
    'wine': 'wijn',
    'winged bean': 'boon',
    'winter melon': 'meloen',
    'yardlong bean': 'bonen',
    'yarrow': 'duizendblad',
    'yeast': 'gist',
    'yellow summer squash': 'zomerpompoen',
    'yogurt': 'yoghurt',
    'yolk': 'dooier',
    'zucchini': 'courgette'
}